// Generates WAUX's privacy avatars: glossy 3D characters drawn as inline SVG
// (no network, no image files). Each is a lit body (sphere, rounded cube or
// capsule) on a tinted tile, with eyes, a visor or an antenna. Emitted as
// CSS custom properties --waux-av-0 .. --waux-av-9.

const BODIES = ['sphere', 'cube', 'capsule'];
const FACES = ['dots', 'visor', 'happy', 'wink'];
const EXTRAS = ['none', 'antenna', 'halo', 'leaf', 'none'];

// [tile hue, body hue] pairs, chosen to read well on dark and light themes.
const PALETTE = [
  [18, 28],
  [205, 195],
  [152, 140],
  [268, 280],
  [38, 45],
  [332, 345],
  [96, 88],
  [186, 172],
  [228, 240],
  [0, 12],
];

function body(kind, fill) {
  if (kind === 'cube') return `<rect x="15" y="17" width="34" height="34" rx="11" fill="${fill}"/>`;
  if (kind === 'capsule') return `<rect x="19" y="12" width="26" height="41" rx="13" fill="${fill}"/>`;
  return `<circle cx="32" cy="34" r="18" fill="${fill}"/>`;
}

function face(kind) {
  const eye = (x) =>
    `<ellipse cx="${x}" cy="33" rx="2.6" ry="3.4" fill="#16171a"/><circle cx="${x + 0.9}" cy="31.8" r="0.9" fill="#fff"/>`;
  switch (kind) {
    case 'visor':
      return `<rect x="20" y="28.5" width="24" height="9" rx="4.5" fill="#16171a"/><rect x="23" y="31" width="9" height="2" rx="1" fill="#fff" opacity=".55"/>`;
    case 'happy':
      return `<path d="M23.5 34q3-4 6 0M34.5 34q3-4 6 0" fill="none" stroke="#16171a" stroke-width="2.4" stroke-linecap="round"/><path d="M28 40q4 3 8 0" fill="none" stroke="#16171a" stroke-width="2" stroke-linecap="round"/>`;
    case 'wink':
      return `${eye(26)}<path d="M35 33.5h6" stroke="#16171a" stroke-width="2.4" stroke-linecap="round"/><circle cx="32" cy="40.5" r="1.6" fill="#16171a"/>`;
    default:
      return `${eye(26)}${eye(38)}`;
  }
}

function extra(kind, hue) {
  switch (kind) {
    case 'antenna':
      return `<path d="M32 16V8" stroke="#16171a" stroke-width="2" stroke-linecap="round"/><circle cx="32" cy="7" r="3" fill="hsl(${hue} 90% 70%)" stroke="#16171a" stroke-width="1.5"/>`;
    case 'halo':
      return `<ellipse cx="32" cy="12" rx="11" ry="3" fill="none" stroke="hsl(48 95% 70%)" stroke-width="2.4"/>`;
    case 'leaf':
      return `<path d="M32 17c0-6 5-9 10-9-1 6-5 9-10 9z" fill="hsl(120 55% 52%)" stroke="#16171a" stroke-width="1.4"/>`;
    default:
      return '';
  }
}

export function avatarSvg(i) {
  const [tile, hue] = PALETTE[i % PALETTE.length];
  const kind = BODIES[i % BODIES.length];
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<defs>
<linearGradient id="t" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="hsl(${tile} 55% 30%)"/><stop offset="1" stop-color="hsl(${tile + 25} 50% 14%)"/></linearGradient>
<radialGradient id="b" cx=".34" cy=".28" r=".85"><stop offset="0" stop-color="hsl(${hue} 95% 88%)"/><stop offset=".35" stop-color="hsl(${hue} 80% 64%)"/><stop offset="1" stop-color="hsl(${hue} 70% 30%)"/></radialGradient>
<radialGradient id="g" cx=".5" cy=".5" r=".5"><stop offset="0" stop-color="hsl(${hue} 90% 70%)" stop-opacity=".45"/><stop offset="1" stop-color="hsl(${hue} 90% 70%)" stop-opacity="0"/></radialGradient>
</defs>
<rect width="64" height="64" fill="url(#t)"/>
<circle cx="32" cy="34" r="27" fill="url(#g)"/>
<ellipse cx="32" cy="56" rx="15" ry="3.6" fill="#000" opacity=".35"/>
${extra(EXTRAS[i % EXTRAS.length], hue)}
${body(kind, 'url(#b)')}
<ellipse cx="25" cy="23" rx="6" ry="3.6" fill="#fff" opacity=".42" transform="rotate(-28 25 23)"/>
${face(FACES[i % FACES.length])}
</svg>`;
  return svg.replace(/\n/g, '');
}

const uri = (svg) => `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;

export function avatarsCss() {
  const vars = PALETTE.map((_, i) => `--waux-av-${i}:${uri(avatarSvg(i))};`).join('');
  // One avatar per chat, chosen by the chat row's index; group senders by row.
  const rows = PALETTE.map((_, i) => `html.waux #pane-side [data-testid$="${i}"]{--waux-av:var(--waux-av-${i})}`).join('');
  const senders = [1, 2, 3].map((k) => `html.waux #main [role="row"]:nth-child(3n+${k}){--waux-av:var(--waux-av-${k + 3})}`).join('');
  return `/* Generated by scripts/avatars.mjs */html.waux{${vars}}${rows}${senders}`;
}
